### ISSUE TITLE
Problem with eclipsify command 

### ISSUE THREAD

**Issue by ahmetb** [erwan/playoauthclient#4]
I have included oauth-1.0 to my play project config and then tried to eclipsify and got the following error:

~ play! 1.1RC2-99-ga1a8239, http://www.playframework.org
~
Traceback (most recent call last):
  File "/home/alp/play/play", line 111, in <module>
    cmdloader.commands[play_command].execute(command=play_command, app=play_app, args=remaining_args, env=play_env, cmdloader=cmdloader)
  File "/home/alp/play/framework/pym/play/commands/eclipse.py", line 123, in execute
    execfile(commands)
  File "/home/alp/play/modules/oauth-1.0/commands.py", line 5, in <module>
    if play_command == 'hello':
NameError: name 'play_command' is not defined

**Comment by christopheroussy** [comment]
Comment out the contents of commands.py and try again.
